### ISSUE TITLE
Enable Background Video for new Playnite 9 Version

### ISSUE THREAD

**Issue by TacticalBill** [davidkgriggs/PS5ish#12]
Since updating to Playnite 9, the PS5ish theme no longer allows for a background video to play on the main game selection screen.

The instructions here do not seem to work for the new version: https://github.com/davidkgriggs/PS5ish/wiki#background-image-background-video-background-music--profile-picture-installation

**Comment by davidkgriggs** [comment]
You are correct the wiki is out of date. I have updated it to show it is just for Playnite 8. Video backgrounds have not been implemented in v4 for Playnite 9. I will add it in and then close this issue once its done.

**Comment by Brandon1212b** [comment]
I am not able to get background videos to run following these steps. https://github.com/davidkgriggs/PS5ish/wiki/Playnite-8:-Extra-Metadata-Tools-Integration
