### ISSUE TITLE
All bugs found

### ISSUE THREAD

**Issue by LuKa8989** [davidkgriggs/PS5ish#15]
Text "cerca" and "impostazioni" not centered in the Italian localization, selecting the ps store icon remains the name of the game next to it, the video trailers do not start automatically and correct the possibility to change the text "Play" on the screen where there is the game trailer in "Start game" in the Italian localization, we had already talked about it on discord but I also add it here as a reminder, thank you very much

**Comment by davidkgriggs** [comment]
I believe all are fixed in v4.4.0
