### ISSUE TITLE
PS5ish 4.4.0

### ISSUE THREAD

**Issue by LuKa8989** [davidkgriggs/PS5ish#19]
Meanwhile, thanks for the latest PS5ish update, there are some things that have not yet been optimally corrected, on the home screen the text "cerca" and "impostazioni" are not yet centered correctly I attach images.
The animation when starting the theme is not correct, it starts asynchronously, I am attaching videos.
The name of the PSstore icon is poorly localized in Italian, it must not be "Pagina del negozio" but "PlayStation Store", thanks again for your work
![20211207_123107](https://user-images.githubusercontent.com/93041304/145025201-1c74db52-93ea-4e49-8aaa-05fb5c5720c0.jpg)
![20211207_123118](https://user-images.githubusercontent.com/93041304/145025206-2547dd2e-06bc-4963-8e96-b81e45e03daf.jpg)
![20211207_123357](https://user-images.githubusercontent.com/93041304/145025208-334c4735-0ea5-461b-9122-cf358e805b04.jpg)

https://user-images.githubusercontent.com/93041304/145025212-8cf10e9d-df1a-4aea-a541-9562c9d7524a.mp4

**Comment by davidkgriggs** [comment]
I cannot get the labels for Search or Settings to centre anymore than they are. It will break too many things.
Your into issue is easily sorted, set the intro length in the DKG Theme Modifier to be the same or 1 second longer than your video intro.
