### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by oOXenonTitareOo** [davidkgriggs/PS5ish#24]
Hello!

I have found some bugs with the hungarian language.

1. Start game aka "Indítás Game" should be "Játék Indítása" - Feels like half translated
2. Now check on the right. "Earned" should be "Elért" and "Progress" should be "Előrehaladás". This could be due to an addon.
![image](https://user-images.githubusercontent.com/43107574/147815633-015a4454-bba9-4d4d-8bd7-85f6bb023bf1.png)

**Comment by davidkgriggs** [comment]
Only fields that are used directly from Playnite get translated. Any extra fields won't get translated. But I have added the option to edit those fields to be what you want in the DKG Theme Modifier. Install that extension and then you will see a Labels tab. Make your changes and then Apply Changes for them to. Be set.
