### ISSUE TITLE
Not an issue, but rather a new feature idea

### ISSUE THREAD

**Issue by oOXenonTitareOo** [davidkgriggs/PS5ish#25]
Hello!

Can you add in micro videos / trailes to the background as seen in this video? 
https://www.youtube.com/watch?v=aeGUnTl3cSw&t=39s&ab_channel=WilliamLeGod

And can you add in the intro of the actual ps5 startup please?
https://www.youtube.com/watch?v=b6Mp13Ole90&ab_channel=twishesbot

Thanks!

**Comment by davidkgriggs** [comment]
Micro trailers / trailers added to main screen in v4.5.0, no ETA on release.

You can add the intro yourself, you need to download the video and then follow the instructions for the -- Video Intro -- section on https://playnite.link/forum/thread-492.html
