### ISSUE TITLE
Feature Request - Add more than 2 Filter preset on Main page

### ISSUE THREAD

**Issue by acejoker6** [davidkgriggs/PS5ish#31]
The main page only displays the first 2 filter of Playnite's filter presets. 

Going in 'All Games' while full screen displays all the filter presets.

I understand the theme is meant to be an as close as possible replication of the PS5 UI but it would be nice to have this functionality implemented as an optional customization.

**Comment by LuKa8989** [comment]
The sense of the theme is to be 1: 1 equal to the ps5 dashboard that's why there are only two filters on the home screen

**Comment by davidkgriggs** [comment]
An option will be added in the next release of the theme and DKG Theme Modifier to enable all Filter Presets on the Main screen.
