### ISSUE TITLE
Icons in settings and filters do not appear

### ISSUE THREAD

**Issue by unknowbrain010** [davidkgriggs/PS5ish#33]
As the title says, any solution?
I have tried the xbox theme and this does not happen.
![menu2](https://user-images.githubusercontent.com/100535331/155897509-e39d782d-fa40-4957-8c8b-0dc9997104cc.png)
![menu3](https://user-images.githubusercontent.com/100535331/155897518-b7ed39b1-6545-4e4e-aa6f-fac655522846.png)
![filters](https://user-images.githubusercontent.com/100535331/155897520-511e6bfa-97db-4be4-beb3-e194972637f0.png)
![menu](https://user-images.githubusercontent.com/100535331/155897529-283c796f-938e-4bae-9811-0f1e5fa5554e.png)

**Comment by davidkgriggs** [comment]
There is a font that comes with windows 10 called segoe mdl2 assets. If you don't have that font installed you just need to install it to get the icons.

**Comment by unknowbrain010** [comment]
it worked thanks
