### ISSUE TITLE
No PS5ish folder

### ISSUE THREAD

**Issue by FuZe64** [davidkgriggs/PS5ish#6]
When I tried to use your video background, there is no PS5ish folder to put it on. Hope this'll get fixed!

**Comment by davidkgriggs** [comment]
I'm not sure what you mean? If you have installed the theme then there will be a PS5ish folder in the themes directory for Playnite. If you're using Extra Metadata Tools to install the video background you just need to use that to select the video file and it will copy it to the appropriate place.
