### ISSUE TITLE
Playnite fullscreen HDMI input loop & window remains focused even when opening game #2336

### ISSUE THREAD

**Issue by jamie9090** [davidkgriggs/PS5ish#7]
Thanks for an amazing playnite theme! It's amazing. 

Using Ps5ish (although I don't know if it's related), full screen seems to occasionally get into an input loop with hdmi. I only have this issue in playnite, no other games or apps.

See video: https://linksharing.samsungcloud.com/qOJSlGGlAsdv

Maybe HDR related? That's what the pop up on TV in top right corner says, "HDR". TV is LG CX.

Alongside this, opening up a game, I can still here Playnites background music. And ingame I get a double input issue, common when Playnite still has focus somehow in the background. I can fix this by going to desktop, opening playnite, minimising and then going back into game. I can't fix the input issue though.

Makes me feel like perhaps there's an issue with how playnite is going full screen? Maybe it's a borderless window that's losing focus?

Both issues seem related, in my opinion (an uneducated one 😂).

Cross posted here: https://github.com/JosefNemec/Playnite/issues/2336

**Comment by davidkgriggs** [comment]
Does this happen with the other themes too or just this one?

**Comment by jamie9090** [comment]
Just tested Default, I didn't experiecne the issue. So I think it may be only PS5ish.

PS5ish should become the new default though! ;)

My non-developer opinion is that it has something to do with how it's going full screen. 

I commonly get the same "input switch" (eg: flickers black then shows HDR at the top) when leaving a full screen game. But that happens only once, not continuosuly as I'm currently expereincing in PS5ish

I can test other custom themes if you like. Any ideas?

**Comment by jamie9090** [comment]
Also, love the fact you're continuing to update these themes. They're always getting better!

Would be cool to one day get background videos going for PS5ish.

**Comment by davidkgriggs** [comment]
Background videos are already supported by PS5ish.
If you could test another theme like XBOXSERIESish and let me know.
I can only think it is a MediaElement issue, however I can't reproduce it to see how to fix it.

**Comment by jamie9090** [comment]
Same issue on SIMPLEISH and XBOXISH 😔

**Comment by davidkgriggs** [comment]
Do you have Extra Metadata Tools installed? Do you have background video and music applied?

**Comment by jamie9090** [comment]
Yep! I’m using all the features, including trailers. From: davidkgriggsSent: Thursday, 20 May 2021 2:41 AMTo: davidkgriggs/PS5ishCc: jamie9090; AuthorSubject: Re: [davidkgriggs/PS5ish] Playnite fullscreen HDMI input loop & window remains focused even when opening game #2336 (#7) Do you have Extra Metadata Tools installed? Do you have background video and music applied?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by davidkgriggs** [comment]
OK you'll need to delete the background video, any background music and trailers. Then test. If your TV is getting confused signals about hdr then it must be to do with a media element that is playing and confusing it. The only way to see what would be to delete all media files that are currently playing to be sure they cannot run in the background behind game images etc. Once you have no media elements of the problem still happens then I'm really not sure.

**Comment by jamie9090** [comment]
Unfortunately after disabling the videos and trailers, I didn't see any
improvement.

Playnite sounds works fine as the default theme works with it.

I disabled HDR, and I still got the issue. So I don't think it's related to
HDR. I think the HDR banner only shows up because Windows is HDR. I think
it's getting conflicting signals from the theme.

Is there a chance the Playnite window is losing focus, or there's something
different about the full screen mode implementation across the DKG themes?

I generally see this happen when in situations when I'm exiting or alt
tabbing away from a full screen game, as the signal is changing (and it
only happens once so it's not an issue not the looping I see in ps5ish)

**Comment by davidkgriggs** [comment]
Did you physically delete the video files or just disable them in the DKG Modifier? Disabling them in the modifier just hides them from the view but they can still be loaded in the background. So you will need to physically delete the video files to be sure they are not being loaded. There is no difference with my themes other than it has Media Elements playing. These media elements close when Playnite is no longer in focus. This could be the issue. There is this theme https://playnite.link/forum/thread-534.html which is made by someone else but uses the same media elements for background video. You'll need to follow its guide to get the background video working as it's a different set up to mine. If this theme also causes the problem once set up with background video then it will prove if it is the Media Elements causing your issue.

**Comment by jamie9090** [comment]
I was able to get this working after deleting everything then reinstalling everything.

I think it's got something to do with Extra Metadata Tools (even without videos, as I had deleted them).

Thank you for your help!

**Comment by jamie9090** [comment]
Just a quick heads up, I just ended up moving to Simpleish (I love the new version). 

I was able to easily replicate the issue by enabling video covers, then disabling it fixed it. 

All trailers have been deleted. 

However, I still see the issue now when going into game details view. This occurs every second time going into that view or so. 

I am using the default video background.

If mediaelements is the issue, is that fixable by anyone, even myself? Or is that something I might just need to accept 😭 😂

**Comment by davidkgriggs** [comment]
It is a strange one. Media Elements in WPF use Windows Media Player to play the media. You can't change that. It would seem that when Windows Media player opens the video files it causes your TV to see a different profile being used, I can force my TV to do something similar if you I use Media Player Classic and get it to switch to HDR for HDR content. However my TV does not have any issues with Media Elements in WPF. What is your TV model number? What is your PC specs? I guess someone else might have had a similar issue with just video players in general and it might help to find a solution.

**Comment by jamie9090** [comment]
I think was fixed in the latest  nvidia driver update. I've got it all working with trailers now.

**Comment by davidkgriggs** [comment]
Brilliant! Thanks for the update on this.
