### ISSUE TITLE
Showing recently played, favorites on the tab bar in PS5ish theme instead of Media

### ISSUE THREAD

**Issue by Rishang007** [davidkgriggs/PS5ish#8]
Hello,
I really liked the PS5ish theme but I have a suggestion to remove the media bar from the top and add recently played, favorites and all the original tabs from the default theme beacuse the LB and RB action is still the same and also PS5ish theme's tab position is on the top so the LB and RB action seems intuitive.

![InkedScreenshot 2021-05-30 13 38 39_LI](https://user-images.githubusercontent.com/64747233/120097159-99fb7180-c14c-11eb-8c73-fb8f61caf555.jpg)

**Comment by davidkgriggs** [comment]
This is already possible. Download the DKG Theme Modifier. Then un-tick Default Mode, you can then go into the Custimise Tab and choose Playnite Tabs. The preview image will hell you see what you've changed.
